insert into Raza (ID, NOMBRE) values
(1, 'Alano'),
(2, 'Alaskan Malamute '),
(3, 'American Staffordshire Terrier '),
(4, 'American Water Spaniel '),
(5, 'Antiguo Pastor Inglés'),
(6, 'Basset Azul de Gaseogne '),
(7, 'Basset Hound '),
(8, 'Basset leonado de Bretaña'),
(9, 'Beagle '),
(10, 'Bearded Collie '),
(11, 'Bichón Maltés '),
(12, 'Bobtail '),
(13, 'Border Collie '),
(14, 'Boston Terrier '),
(15, 'Boxer '),
(16, 'Bull Terrier '),
(17, 'Bulldog Americano '),
(18, 'Bulldog Francés '),
(19, 'Bulldog Inglés'),
(20, 'Caniche '),
(21, 'Carlino'),
(22, 'Chihuahua'),
(23, 'Cirneco del Etna'),
(24, 'Chow Chow '),
(25, 'Cocker Spaniel Americano '),
(26, 'Cocker Spaniel Inglés'),
(27, 'Dálmata '),
(28, 'Dobermann '),
(29, 'Dogo Alemán'),
  (30, 'Dogo Argentino'),
  (31, 'Dogo de Burdeos'),
  (32, 'Finlandés'),
  (33, 'Fox Terrier de pelo liso '),
  (34, 'Fox Terrier '),
  (35, 'Foxhound Americano'),
  (36, 'Foxhound Inglés'),
  (37, 'Galgo Afgano '),
  (38, 'Gigante de los Pirineos'),
  (39, 'Golden Retriever '),
  (40, 'Gos d''Atura '),
  (41, 'Gran Danés'),
  (42, 'Husky Siberiano'),
  (43, 'Laika de Siberia Occidental'),
  (44, 'Laika Ruso-europeo'),
  (45, 'Labrador Retriever'),
  (46, 'Mastín del Pirineo'),
  (47, 'Mastin del Tibet'),
  (48, 'Mastín Español'),
  (49, 'Mastín Napolitano'),
  (50, 'Pastor Alemán'),
  (51, 'Pastor Australiano'),
  (52, 'Pastor Belga '),
  (53, 'Pastor de Brie'),
  (54, 'Pastor de los Pirineos de Cara Rosa '),
  (55, 'Pekinés'),
  (56, 'Perdiguero Chesapeake Bay'),
  (57, 'Perdiguero de Drentse'),
  (58, 'Perdiguero de Pelo lido'),
  (59, 'Perdiguero de pelo rizado'),
  (60, 'Perdiguero Portugués'),
  (61, 'Pitbull '),
  (62, 'Podenco Ibicenco'),
  (63, 'Podenco Portugués'),
  (64, 'Presa canario '),
  (65, 'Presa Mallorquin'),
  (66, 'Rottweiler '),
  (67, 'Rough Collie'),
  (68, 'Sabueso Español'),
  (69, 'Sabueso Hélenico'),
  (70, 'Sabueso Italiano'),
  (71, 'Sabueso Suizo'),
  (72, 'Samoyedo '),
  (73, 'San Bernardo '),
  (74, 'Scottish Terrier '),
  (75, 'Setter Irlandés '),
  (76, 'Shar Pei '),
  (77, 'Shiba Inu '),
  (78, 'Siberian Husky '),
  (79, 'Staffordshire Bull Terrier'),
  (80, 'Teckel'),
  (81, 'Terranova '),
  (82, 'Terrier Australiano'),
  (83, 'Terrier Escocés '),
  (84, 'Terrier Irlandés '),
  (85, 'Terrier Japonés'),
  (86, 'Terrier Negro Ruso'),
  (87, 'Terrier Norfolk'),
  (88, 'Terrier Norwich'),
  (89, 'Yorkshire Terrier');
