insert into Raza (ID, NOMBRE) values (1, 'Alano');
insert into Raza (ID, NOMBRE) values (2, 'Alaskan Malamute ');
insert into Raza (ID, NOMBRE) values (3, 'American Staffordshire Terrier ');
insert into Raza (ID, NOMBRE) values (4, 'American Water Spaniel ');
insert into Raza (ID, NOMBRE) values (5, 'Antiguo Pastor Inglés');
insert into Raza (ID, NOMBRE) values (6, 'Basset Azul de Gaseogne ');
insert into Raza (ID, NOMBRE) values (7, 'Basset Hound ');
insert into Raza (ID, NOMBRE) values (8, 'Basset leonado de Bretaña');
insert into Raza (ID, NOMBRE) values (9, 'Beagle ');
insert into Raza (ID, NOMBRE) values (10, 'Bearded Collie ');
insert into Raza (ID, NOMBRE) values (11, 'Bichón Maltés ');
insert into Raza (ID, NOMBRE) values (12, 'Bobtail ');
insert into Raza (ID, NOMBRE) values (13, 'Border Collie ');
insert into Raza (ID, NOMBRE) values (14, 'Boston Terrier ');
insert into Raza (ID, NOMBRE) values (15, 'Boxer ');
insert into Raza (ID, NOMBRE) values (16, 'Bull Terrier ');
insert into Raza (ID, NOMBRE) values (17, 'Bulldog Americano ');
insert into Raza (ID, NOMBRE) values (18, 'Bulldog Francés ');
insert into Raza (ID, NOMBRE) values (19, 'Bulldog Inglés');
insert into Raza (ID, NOMBRE) values (20, 'Caniche ');
insert into Raza (ID, NOMBRE) values (21, 'Carlino');
insert into Raza (ID, NOMBRE) values (22, 'Chihuahua');
insert into Raza (ID, NOMBRE) values (23, 'Cirneco del Etna');
insert into Raza (ID, NOMBRE) values (24, 'Chow Chow ');
insert into Raza (ID, NOMBRE) values (25, 'Cocker Spaniel Americano ');
insert into Raza (ID, NOMBRE) values (26, 'Cocker Spaniel Inglés');
insert into Raza (ID, NOMBRE) values (27, 'Dálmata ');
insert into Raza (ID, NOMBRE) values (28, 'Dobermann ');
insert into Raza (ID, NOMBRE) values (29, 'Dogo Alemán');
insert into Raza (ID, NOMBRE) values (30, 'Dogo Argentino');
insert into Raza (ID, NOMBRE) values (31, 'Dogo de Burdeos');
insert into Raza (ID, NOMBRE) values (32, 'Finlandés');
insert into Raza (ID, NOMBRE) values (33, 'Fox Terrier de pelo liso ');
insert into Raza (ID, NOMBRE) values (34, 'Fox Terrier ');
insert into Raza (ID, NOMBRE) values (35, 'Foxhound Americano');
insert into Raza (ID, NOMBRE) values (36, 'Foxhound Inglés');
insert into Raza (ID, NOMBRE) values (37, 'Galgo Afgano ');
insert into Raza (ID, NOMBRE) values (38, 'Gigante de los Pirineos');
insert into Raza (ID, NOMBRE) values (39, 'Golden Retriever ');
insert into Raza (ID, NOMBRE) values (40, 'Gos d''Atura ');
insert into Raza (ID, NOMBRE) values (41, 'Gran Danés');
insert into Raza (ID, NOMBRE) values (42, 'Husky Siberiano');
insert into Raza (ID, NOMBRE) values (43, 'Laika de Siberia Occidental');
insert into Raza (ID, NOMBRE) values (44, 'Laika Ruso-europeo');
insert into Raza (ID, NOMBRE) values (45, 'Labrador Retriever');
insert into Raza (ID, NOMBRE) values (46, 'Mastín del Pirineo');
insert into Raza (ID, NOMBRE) values (47, 'Mastin del Tibet');
insert into Raza (ID, NOMBRE) values (48, 'Mastín Español');
insert into Raza (ID, NOMBRE) values (49, 'Mastín Napolitano');
insert into Raza (ID, NOMBRE) values (50, 'Pastor Alemán');
insert into Raza (ID, NOMBRE) values (51, 'Pastor Australiano');
insert into Raza (ID, NOMBRE) values (52, 'Pastor Belga ');
insert into Raza (ID, NOMBRE) values (53, 'Pastor de Brie');
insert into Raza (ID, NOMBRE) values (54, 'Pastor de los Pirineos de Cara Rosa ');
insert into Raza (ID, NOMBRE) values (55, 'Pekinés');
insert into Raza (ID, NOMBRE) values (56, 'Perdiguero Chesapeake Bay');
insert into Raza (ID, NOMBRE) values (57, 'Perdiguero de Drentse');
insert into Raza (ID, NOMBRE) values (58, 'Perdiguero de Pelo lido');
insert into Raza (ID, NOMBRE) values (59, 'Perdiguero de pelo rizado');
insert into Raza (ID, NOMBRE) values (60, 'Perdiguero Portugués');
insert into Raza (ID, NOMBRE) values (61, 'Pitbull ');
insert into Raza (ID, NOMBRE) values (62, 'Podenco Ibicenco');
insert into Raza (ID, NOMBRE) values (63, 'Podenco Portugués');
insert into Raza (ID, NOMBRE) values (64, 'Presa canario ');
insert into Raza (ID, NOMBRE) values (65, 'Presa Mallorquin');
insert into Raza (ID, NOMBRE) values (66, 'Rottweiler ');
insert into Raza (ID, NOMBRE) values (67, 'Rough Collie');
insert into Raza (ID, NOMBRE) values (68, 'Sabueso Español');
insert into Raza (ID, NOMBRE) values (69, 'Sabueso Hélenico');
insert into Raza (ID, NOMBRE) values (70, 'Sabueso Italiano');
insert into Raza (ID, NOMBRE) values (71, 'Sabueso Suizo');
insert into Raza (ID, NOMBRE) values (72, 'Samoyedo ');
insert into Raza (ID, NOMBRE) values (73, 'San Bernardo ');
insert into Raza (ID, NOMBRE) values (74, 'Scottish Terrier ');
insert into Raza (ID, NOMBRE) values (75, 'Setter Irlandés ');
insert into Raza (ID, NOMBRE) values (76, 'Shar Pei ');
insert into Raza (ID, NOMBRE) values (77, 'Shiba Inu ');
insert into Raza (ID, NOMBRE) values (78, 'Siberian Husky ');
insert into Raza (ID, NOMBRE) values (79, 'Staffordshire Bull Terrier');
insert into Raza (ID, NOMBRE) values (80, 'Teckel');
insert into Raza (ID, NOMBRE) values (81, 'Terranova ');
insert into Raza (ID, NOMBRE) values (82, 'Terrier Australiano');
insert into Raza (ID, NOMBRE) values (83, 'Terrier Escocés ');
insert into Raza (ID, NOMBRE) values (84, 'Terrier Irlandés ');
insert into Raza (ID, NOMBRE) values (85, 'Terrier Japonés');
insert into Raza (ID, NOMBRE) values (86, 'Terrier Negro Ruso');
insert into Raza (ID, NOMBRE) values (87, 'Terrier Norfolk');
insert into Raza (ID, NOMBRE) values (88, 'Terrier Norwich');
insert into Raza (ID, NOMBRE) values (89, 'Yorkshire Terrier');
